--- # Fast Start :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: black-baker
  namespace: black
  labels:
    app: black-baker
spec:
  selector:
    matchLabels:
      app: black-baker
  replicas: 1
  template:
    metadata:
      labels:
        app: black-baker
    spec:
      containers:
        name: black-baker
        image: ibmicpcoc/baker:latest
        imagePullPolicy: Always
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: black-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: black-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
