--- # Fast Start :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: black-eagle
  namespace: black
  labels:
    app: black-eagle
spec:
  selector:
    matchLabels:
      app: black-eagle
  replicas: 1
  template:
    metadata:
      labels:
        app: black-eagle
    spec:
      containers:
      - name: black-eagle
        image: ibmicpcoc/eagle:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4100
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: black-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: black-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: black-eagle
  namespace: black
  labels:
    app: black-eagle
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4100
      protocol: TCP
      name: black-eagle
  selector:
    app: black-eagle
---
